resources:
  jobs:
    L1_2_provisioned_throughput_deployment:
      name: L1-2-provisioned-throughput-deployment
      budget_policy_id: ${var.budget_policy_id}
      tags:
        project_name: "llmops-databricks-course-MartijnCauchy"

      environments:
        - environment_key: default
          spec:
            environment_version: "4"
            dependencies:
              - ../dist/*.whl

      tasks:
        - task_key: run_notebook
          environment_key: default
          notebook_task:
            notebook_path: ../notebooks/L1_2_provisioned_throughput_deployment.py
            base_parameters:
              env: ${bundle.target}
              git_sha: "${var.git_sha}"
              run_id: "{{job.run_id}}"
